Repository AY2324S2-CS2113-T15-1/tp, pull requests merged in 2024-04, with the labels that each got.

#90 Add UML diagram
  docs/diagrams/LongAh.puml
Labels: priority.Medium

#86 View chart
  build.gradle
  src/main/java/longah/commands/ViewCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/util/Chart.java
  src/test/java/longah/util/ChartTest.java
Labels: priority.Medium

#91 Fix welcome message
  src/main/java/longah/LongAh.java
  src/main/java/longah/handler/UI.java
  text-ui-test/EXPECTED1.TXT
Labels: type.Bug

#89 Group Management
  docs/UserGuide.md
  src/main/java/longah/LongAh.java
  src/main/java/longah/commands/HelpCommand.java
  src/main/java/longah/commands/SwitchCommand.java
  src/main/java/longah/commands/add/AddCommand.java
  src/main/java/longah/commands/add/AddGroupCommand.java
  src/main/java/longah/commands/delete/DeleteCommand.java
  src/main/java/longah/commands/delete/DeleteGroupCommand.java
  src/main/java/longah/commands/list/ListCommand.java
  src/main/java/longah/commands/list/ListGroupsCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/GroupList.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
  text-ui-test/EXPECTED1.TXT
  text-ui-test/input1.txt
Labels: priority.Medium

#116 Setup for PPP
  docs/AboutUs.md
  docs/README.md
  docs/team/1simjustin.md
  docs/team/djleong01.md
  docs/team/feathersre.md
  docs/team/haowern98.md
  docs/team/jing-xiang.md
Labels: type.Task, priority.Medium

#95 Time filter
  src/main/java/longah/commands/filter/FilterCommand.java
  src/main/java/longah/commands/filter/FilterDateTimeCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/node/DateTime.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
Labels: priority.Medium

#118 Add PPP
  docs/team/jing-xiang.md
Labels: priority.High

#156 PED fixes for DateTime and TransactionList methods
  src/main/java/longah/commands/filter/FilterDateTimeCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/node/DateTime.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
  src/test/java/longah/util/TransactionListTest.java
Labels: priority.High

#154 General Documentation Improvements
  docs/DeveloperGuide.md
  docs/diagrams/CommandExecutionSequence.puml
  docs/diagrams/CommandExecutionSequenceDiagram.png
  docs/diagrams/CommandInheritance.png
  docs/diagrams/CommandInheritance.puml
  docs/diagrams/MembersFileSample.png
  docs/diagrams/StorageHandlerInitSequenceDiagram.png
  docs/diagrams/StorageHandlerInitSequenceDiagram.puml
  docs/diagrams/StorageHandlerSequence.puml
  docs/diagrams/StorageHandlerSequenceDiagram.png
  docs/diagrams/TransactionsFileSample.png
  docs/diagrams/main.png
  docs/diagrams/main.puml
  docs/team/1simjustin.md
Labels: type.Documentation

#121 Fix Transaction Formatting and Add Command Shortcuts
  docs/UserGuide.md
  src/main/java/longah/commands/ChartCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
  src/test/java/longah/util/TransactionListTest.java
Labels: type.Task, priority.Medium

#153 Fixes for PED Issues
  .gitignore
  docs/UserGuide.md
  src/main/java/longah/LongAh.java
  src/main/java/longah/commands/edit/EditCommand.java
  src/main/java/longah/commands/edit/EditMemberCommand.java
  src/main/java/longah/commands/find/FindBorrowerCommand.java
  src/main/java/longah/commands/find/FindLenderCommand.java
  src/main/java/longah/commands/find/FindTransactionCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/handler/Logging.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/util/GroupList.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/Subtransaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/MemberListTest.java
  src/test/java/longah/util/TransactionListTest.java
  text-ui-test/EXPECTED1.TXT
Labels: type.Bug

#155 DG Additions
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/Flowchart.png
  docs/diagrams/Member.png
  docs/team/1simjustin.md
  src/main/java/longah/commands/ExitCommand.java
  src/main/java/longah/handler/UI.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/util/MemberList.java
  src/test/java/longah/handler/StorageHandlerTest.java
  src/test/java/longah/util/ChartTest.java
  src/test/java/longah/util/MemberListTest.java
  text-ui-test/EXPECTED1.TXT
Labels: type.Documentation

#164 Add ClearCommand warning message
  src/main/java/longah/commands/ClearCommand.java
Labels: severity.Low

#166 Improve UI elements and update help menu
  docs/UserGuide.md
  src/main/java/longah/LongAh.java
  src/main/java/longah/commands/HelpCommand.java
  src/main/java/longah/commands/SwitchCommand.java
  src/main/java/longah/commands/delete/DeleteGroupCommand.java
  src/main/java/longah/commands/edit/EditMemberCommand.java
  src/main/java/longah/commands/edit/EditTransactionCommand.java
  src/main/java/longah/commands/filter/FilterDateTimeCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/PINHandler.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/GroupList.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/TransactionListTest.java
  text-ui-test/EXPECTED1.TXT
Labels: priority.High

#160 P0: Fix double representation bug in storage
  src/main/java/longah/commands/list/ListDebtCommand.java
  src/main/java/longah/commands/list/ListGroupsCommand.java
  src/main/java/longah/commands/list/ListMemberCommand.java
  src/main/java/longah/commands/list/ListTransactionCommand.java
  src/main/java/longah/handler/StorageHandler.java
  src/test/java/longah/handler/PINHandlerTest.java
Labels: type.Bug, severity.High

#171 Update UG
  docs/UserGuide.md
  src/main/java/longah/node/Group.java
  text-ui-test/expected_output/EXPECTED3.TXT
Labels: priority.High, type.Documentation

#172 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/CommandExecutionSequence.puml
  docs/diagrams/CommandExecutionSequenceDiagram.png
  docs/diagrams/CommandInheritance.png
  docs/diagrams/CommandInheritance.puml
  docs/diagrams/Member.png
  docs/diagrams/Member.puml
  docs/diagrams/StorageHandlerInitSequenceDiagram.png
  docs/diagrams/StorageHandlerInitSequenceDiagram.puml
  docs/diagrams/main.png
  docs/diagrams/main.puml
Labels: type.Documentation

#178 DG Formatting
  docs/DeveloperGuide.md
Labels: type.Documentation

#175 UG-DG-Updates-v2.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/addDateTimeforDatedTransaction.png
  docs/diagrams/addDateTimeforDatedTransaction.puml
  docs/diagrams/comparingDateTime.png
  docs/diagrams/comparingDateTime.puml
  docs/diagrams/printingDateTime.png
  docs/diagrams/printingDateTime.puml
  src/main/java/longah/util/DateTime.java
Labels: type.Documentation

#183 Update PPP
  docs/team/1simjustin.md
Labels: type.Documentation

#174 Update DG for Group
  docs/DeveloperGuide.md
  docs/diagrams/GroupClass.png
  docs/diagrams/GroupClass.puml
  docs/diagrams/TransactionClass.png
  docs/diagrams/TransactionClass.puml
  docs/diagrams/addTransaction.png
  docs/diagrams/addTransaction.puml
  docs/team/djleong01.md
  src/main/java/longah/node/Group.java
Labels: priority.High, type.Documentation
