Repository AY2324S2-CS2113-T15-1/tp, pull requests merged in 2024-03, with the labels that each got.

#33 Implement General Transaction Solving Algorithm
  src/main/java/longah/GroupList.java
  src/main/java/longah/LongAh.java
  src/main/java/longah/Transaction.java
  src/main/java/longah/TransactionList.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/Subtransaction.java
  src/main/java/longah/util/TransactionList.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#37 Junit test 1
  src/main/java/longah/node/Member.java
  src/test/java/longah/node/MemberTest.java
Labels: priority.Medium

#36 Add TransactionList JUnit test
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/MemberTest.java
  src/test/java/longah/util/TransactionListTest.java
Labels: type.Task

#38 Listing, findDebt and findPayement
  src/main/java/longah/LongAh.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/TransactionListTest.java
  text-ui-test/input.txt
Labels: type.Task

#39 Add Transaction Junit test
  src/main/java/longah/LongAh.java
  src/main/java/longah/node/Transaction.java
  src/test/java/longah/node/TransactionTest.java
Labels: type.Task

#40 Refactor Transaction and add settlement function
  src/main/java/longah/LongAh.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/Subtransaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
  src/test/java/longah/util/TransactionListTest.java
  text-ui-test/input.txt
Labels: priority.High

#41 Data Storage
  .gitignore
  src/main/java/longah/LongAh.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/StorageHandler.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/node/TransactionTest.java
  src/test/java/longah/util/TransactionListTest.java
Labels: type.Task, priority.High

#44 Add balance recalculation for delete and clear
  src/main/java/longah/LongAh.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/TransactionList.java
Labels: type.Bug, severity.High

#46 Addon implementations for TransactionListFunctions + Logger
  .gitignore
  src/main/java/longah/LongAh.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/exception/LongAhException.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/TransactionListTest.java
Labels: priority.High, severity.Low

#43 Output Solution
  src/main/java/longah/LongAh.java
  src/main/java/longah/commands/ClearCommand.java
  src/main/java/longah/commands/Command.java
  src/main/java/longah/commands/ExitCommand.java
  src/main/java/longah/commands/SettleCommand.java
  src/main/java/longah/commands/add/AddCommand.java
  src/main/java/longah/commands/add/AddMemberCommand.java
  src/main/java/longah/commands/add/AddTransactionCommand.java
  src/main/java/longah/commands/delete/DeleteCommand.java
  src/main/java/longah/commands/delete/DeleteTransactionCommand.java
  src/main/java/longah/commands/find/FindBorrowerCommand.java
  src/main/java/longah/commands/find/FindCommand.java
  src/main/java/longah/commands/find/FindDebtCommand.java
  src/main/java/longah/commands/find/FindLenderCommand.java
  src/main/java/longah/commands/find/FindTransactionCommand.java
  src/main/java/longah/commands/list/ListCommand.java
  src/main/java/longah/commands/list/ListDebtCommand.java
  src/main/java/longah/commands/list/ListMemberCommand.java
  src/main/java/longah/commands/list/ListTransactionCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/CommandParser.java
  src/main/java/longah/handler/InputHandler.java
  src/main/java/longah/handler/StorageHandler.java
  src/main/java/longah/node/Group.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/MemberList.java
  src/main/java/longah/util/Subtransaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/TransactionListTest.java
  text-ui-test/input.txt
Labels: type.Task, priority.Medium

#49 Edit transactions
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/node/Member.java
  src/main/java/longah/node/Transaction.java
  src/main/java/longah/util/TransactionList.java
  src/test/java/longah/util/TransactionListTest.java
Labels: priority.Medium

#53 Improving Ui
  src/main/java/longah/UI.java
  src/main/java/longah/handler/UI.java
Labels: priority.High

#55 Authentication
  src/main/java/longah/LongAh.java
  src/main/java/longah/commands/ResetCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/CommandParser.java
  src/main/java/longah/handler/PINHandler.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High

#61 Add disable authentication feature and improved logic
  src/main/java/longah/handler/PINHandler.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#62 Add help section
  src/main/java/longah/commands/ClearCommand.java
  src/main/java/longah/commands/ExitCommand.java
  src/main/java/longah/commands/HelpCommand.java
  src/main/java/longah/commands/SettleCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/CommandParser.java
  src/main/java/longah/handler/UI.java
Labels: priority.High

#67 Refactor PIN commands and logic
  src/main/java/longah/commands/PINCommand.java
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/CommandParser.java
  src/main/java/longah/handler/PINHandler.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#73 Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/pinhandler longah.png
Labels: priority.Medium

#77 Time logging increments
  docs/DeveloperGuide.md
  src/main/java/longah/exception/ExceptionMessage.java
  src/main/java/longah/handler/StorageHandler.java
  src/main/java/longah/node/Transaction.java
  src/test/java/longah/node/TransactionTest.java
  src/test/java/longah/util/TransactionListTest.java
Labels: priority.Medium

#69 Update user guide
  docs/AboutUs.md
  docs/UserGuide.md
Labels: priority.High
